# Generated by Django 2.1 on 2018-08-11 10:51

from django.db import migrations
from country.models import Country


def create_countries(apps, schema_editor):
    nigeria = Country(name="Nigeria", currency="NGN", iso_code="234", tel_code="234")
    ghana = Country(name="Ghana", currency="GHS", iso_code="233", tel_code="233")
    nigeria.save()
    ghana.save()


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_country_tel_code'),
    ]

    operations = [
        migrations.RunPython(create_countries)
    ]
