# Generated by Django 2.1.2 on 2018-11-08 13:54

from django.db import migrations
from django.conf import settings


def update_site_forward(apps, schema_editor):
    """Set site domain and name."""
    Site = apps.get_model("sites", "Site")
    Site.objects.update_or_create(
        id=settings.SITE_ID,
        defaults={
            "domain": "antcorp.ng",
            "name": "Antcorp",
        },
    )


def update_site_backward(apps, schema_editor):
    """Revert site domain and name to default."""
    Site = apps.get_model("sites", "Site")
    Site.objects.update_or_create(
            id=settings.SITE_ID, defaults={"domain": "antcorp.ng", "name": "Antcorp"}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_set_site_domain_name'),
    ]

    operations = [migrations.RunPython(update_site_forward, update_site_backward)]
