# Generated by Django 2.1 on 2018-08-10 22:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('max_limit', models.DecimalField(decimal_places=2, max_digits=16)),
                ('daily_limit', models.DecimalField(decimal_places=2, max_digits=16)),
                ('monthly_limit', models.DecimalField(decimal_places=2, max_digits=16)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
