# Generated by Django 2.1 on 2018-08-11 11:11

from django.db import migrations
from level.models import Level


def create_levels(apps, schema_editor):
    stream = Level(name="Stream", max_limit=5000, daily_limit=4000,  trading_fees=0.00, monthly_limit=4000, discount=0.00)
    river = Level(name="River", max_limit=20000, daily_limit=6000,  trading_fees=0.00,  monthly_limit=7000, discount=0.00)
    lake = Level(name="Lake", max_limit=30000, daily_limit=10000,  trading_fees=0.00, monthly_limit=8000, discount=0.00)
    ocean = Level(name="Ocean", max_limit=1000000, daily_limit=14000,  trading_fees=0.00, monthly_limit=50000, discount=0.00)

    stream.save()
    river.save()
    lake.save()
    ocean.save()


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0002_referral'),
    ]

    operations = [
        # migrations.RunPython(create_levels)
    ]
