# Generated by Django 2.1.1 on 2018-10-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0004_levelupgraderequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='gh_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='ng_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='trading_fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
    ]
