# Generated by Django 2.1.2 on 2018-10-21 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0005_auto_20181019_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelupgraderequest',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
