# Generated by Django 2.1.2 on 2019-01-07 00:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0007_auto_20181021_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelupgraderequest',
            name='address',
            field=models.CharField(help_text='The Home Address of the user', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='levelupgraderequest',
            name='bvn',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='levelupgraderequest',
            name='dob',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='levelupgraderequest',
            name='govt_id',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='levelupgraderequest',
            name='selfie',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='levelupgraderequest',
            name='social_account',
            field=models.URLField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='levelupgraderequest',
            name='utility_bill',
            field=models.TextField(max_length=400, null=True),
        ),

    ]
