# Generated by Django 2.1.2 on 2019-01-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0008_auto_20190107_0019'),
    ]

    operations = [

    ]
