# Generated by Django 2.1.2 on 2019-01-08 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0009_auto_20190107_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelupgraderequest',
            name='current_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_level', to='level.Level'),
        ),
    ]
