# Generated by Django 2.1.2 on 2019-01-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0011_remove_levelupgraderequest_current_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelupgraderequest',
            name='declined',
            field=models.BooleanField(default=False),
        ),
    ]
