# Generated by Django 2.1.1 on 2018-09-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualdeposit',
            name='ref_code',
            field=models.CharField(default='TEST', editable=False, max_length=10, unique=False),
        ),
    ]
