# Generated by Django 2.1.1 on 2018-09-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_manualdeposit_ref_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualdeposit',
            name='ref_code',
            field=models.CharField(default='42234234BB', editable=False, max_length=10),
        ),
    ]
