# Generated by Django 2.1.1 on 2018-10-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_auto_20180927_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
