# Generated by Django 2.1.1 on 2018-10-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_auto_20181018_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='ref_code',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='manualdeposit',
            name='ref_code',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
