# Generated by Django 2.1.1 on 2018-10-17 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(help_text='The Address of the user', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.ForeignKey(help_text="The user's country", on_delete=django.db.models.deletion.CASCADE, related_name='country', to='country.Country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.ForeignKey(help_text='The current level of the user', on_delete=django.db.models.deletion.CASCADE, related_name='level', to='level.Level'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(help_text='Phone number. Usually saved after the user has verified by sms', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_completed',
            field=models.BooleanField(default=False, help_text='The user has been verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_in_progress',
            field=models.BooleanField(default=False, help_text='The user is still getting verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verified_phone',
            field=models.BooleanField(default=False, help_text='The user has verified their phone number'),
        ),
        migrations.AlterField(
            model_name='userloginhistory',
            name='browser',
            field=models.CharField(help_text='Type of browser used', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='userloginhistory',
            name='ip',
            field=models.GenericIPAddressField(default='0.0.0.0', help_text='The login ip address of the user', null=True),
        ),
        migrations.AlterField(
            model_name='userloginhistory',
            name='time',
            field=models.DateTimeField(auto_now_add=True, help_text='Time login occured'),
        ),
    ]
