# Generated by Django 2.1.2 on 2018-10-20 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181017_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(help_text='The Home Address of the user', max_length=100, null=True)),
                ('utility_bill', models.URLField(null=True)),
                ('social_account', models.URLField(null=True)),
                ('selfie', models.URLField(null=True)),
                ('govt_id', models.URLField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_kyc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
