# Generated by Django 2.1.2 on 2018-11-09 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0003_auto_20181017_1202'),
        ('users', '0003_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=230)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_coin', to='coin.Coin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_deposit_address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
