# Generated by Django 2.1.2 on 2018-11-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181125_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(help_text='User referral code', max_length=20, null=True, unique=True),
        ),
    ]
