# Generated by Django 2.1.2 on 2018-11-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181125_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(help_text='User referral code', max_length=260, null=True, unique=True),
        ),
    ]
