# Generated by Django 2.1.2 on 2018-12-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20181205_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='govt_id',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='selfie',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='utility_bill',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
