# Generated by Django 2.1.2 on 2018-12-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20181212_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='bvn',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
