# Generated by Django 2.1.2 on 2018-12-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userdata_bvn'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='dob',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
