# Generated by Django 2.1 on 2018-08-15 22:12

from django.db import migrations
from coin.models import Coin


def create_coins(apps, schema_editor):
    btc = Coin(name="Bitcoin", symbol="BTC",
               buy_rate=357,
               sell_rate=340,
               fees=0.00,
               logo="https://res.cloudinary.com/py/image/upload/v1516641408/bitcoin_logo_31993-600x337_vk3vpu.jpg")

    btc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
    ]

    operations = [
        # migrations.RunPython(create_coins)
    ]
