# Generated by Django 2.1.1 on 2018-10-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0002_auto_20180815_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='coin',
            name='buy_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='coin',
            name='sell_rate',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
