# Generated by Django 2.1.2 on 2018-11-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_sellorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellorder',
            old_name='amount',
            new_name='amount_sold',
        ),
        migrations.AlterField(
            model_name='sellorder',
            name='address',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
