# Generated by Django 2.1.2 on 2018-11-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20181102_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellorder',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='sellorder',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
