# Generated by Django 2.1.2 on 2018-11-06 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import orders.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_auto_20181102_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('reference_id', models.CharField(max_length=256, unique=True)),
                ('wallet_address', models.CharField(max_length=256)),
                ('status', models.CharField(default='unpaid', max_length=230)),
                ('expiry', models.DateTimeField(default=orders.models.invoice_expiry)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_invoice', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
