# Generated by Django 2.1.2 on 2018-11-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20181106_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='btc_amount',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
    ]
