# Generated by Django 2.1.2 on 2018-11-16 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0003_auto_20181017_1202'),
        ('orders', '0007_invoice_btc_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickServe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.EmailField(max_length=254)),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('address', models.CharField(max_length=256)),
                ('transaction_id', models.CharField(max_length=256)),
                ('reference_id', models.CharField(max_length=256, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_serve_coin', to='coin.Coin')),
            ],
        ),
    ]
