# Generated by Django 2.1.7 on 2019-06-30 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_quickserve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quickserve',
            name='coin',
        ),
    ]
